/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
import modelos.ListaPacientes;
import modelos.Pacientes;

/**
 *
 * @author thayn
 */
public class Cadastro extends javax.swing.JFrame {

    private TelaInicial telaInicial;

    /**
     * Creates new form TelaConsulta
     */
    public Cadastro() {
        initComponents();
    }

    public void MostrarTela(TelaInicial obj) {
        this.telaInicial = obj;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastrarConsulta = new javax.swing.JPanel();
        lblCadastrarConsulta = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblDataConsulta = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jcbJaPaciente = new javax.swing.JCheckBox();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Cadastrar Consulta");

        lblCadastrarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCadastrarConsulta.setText("Cadastrar Consulta");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Nome do(a) Paciente: ");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCPF.setText("CPF:");

        lblDataConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataConsulta.setText("Data da consulta:");

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jcbJaPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbJaPaciente.setText("Já é paciente");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastrarConsultaLayout = new javax.swing.GroupLayout(pnlCadastrarConsulta);
        pnlCadastrarConsulta.setLayout(pnlCadastrarConsultaLayout);
        pnlCadastrarConsultaLayout.setHorizontalGroup(
            pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarConsultaLayout.createSequentialGroup()
                .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastrarConsultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadastrarConsulta)
                            .addGroup(pnlCadastrarConsultaLayout.createSequentialGroup()
                                .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPF)
                                    .addComponent(lblNome)
                                    .addComponent(lblTelefone)
                                    .addComponent(lblDataConsulta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome)
                                    .addComponent(txtTelefone)
                                    .addComponent(txtCPF)
                                    .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)))
                            .addComponent(jcbJaPaciente)))
                    .addGroup(pnlCadastrarConsultaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnCadastrar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlCadastrarConsultaLayout.setVerticalGroup(
            pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastrarConsulta)
                .addGap(18, 18, 18)
                .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastrarConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataConsulta)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jcbJaPaciente)
                .addGap(31, 31, 31)
                .addComponent(btnCadastrar)
                .addGap(138, 138, 138))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCadastrarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCadastrarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (!emptyFields()) {
            validacao();
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JCheckBox jcbJaPaciente;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastrarConsulta;
    private javax.swing.JLabel lblDataConsulta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlCadastrarConsulta;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private boolean emptyFields() {
        boolean empty = true;

        if (txtNome.getText().isEmpty() || txtCPF.getText().isEmpty() || txtTelefone.getText().isEmpty() || txtData.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Todos os campos devem estar preenchidos!");
        } else {

            empty = false;
        }

        return empty;
    }

    private void validacao() {

        String testeCPF = txtCPF.getText();
        boolean palavraCPF = testeCPF.matches("[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2}");
        String testeTelefone = txtTelefone.getText();
        boolean palavraTelefone = testeTelefone.matches("[(][0-9]{2}[)][0-9]{4,5}[-][0-9]{4}");
        String testeData = txtData.getText();
        boolean palavraData = testeData.matches("[0-9]{2}[/][0-9]{2}[/][0-9]{2}");

        if (palavraCPF == true && palavraTelefone && palavraData == true) {
            cadastrar();

            txtNome.setText("");
            txtCPF.setText("");
            txtTelefone.setText("");
            txtData.setText("");
            jcbJaPaciente.setSelected(false);

            txtNome.requestFocus();
        } else if (txtNome.getText().length() < 2) {
            JOptionPane.showMessageDialog(rootPane, "Informe um nome valido");
        } else if (palavraCPF == false) {
            JOptionPane.showMessageDialog(rootPane, "Informe CPF no formato xxx.xxx.xxx-xx");
        } else if (palavraTelefone == false) {
            JOptionPane.showMessageDialog(rootPane, "Informe o telefone no formato (xx)xxxxx-xxxx");
        } else if (palavraData == false) {
            JOptionPane.showMessageDialog(rootPane, "Informe a data no formato xx/xx/xx");
        }

    }

    public void cadastrar() {

        Pacientes pac = new Pacientes();
        pac.setNome(txtNome.getText());
        pac.setCpf(txtCPF.getText());
        pac.setTelefone(txtTelefone.getText());
        pac.setData(txtData.getText());

        if (jcbJaPaciente.isSelected()) {
            pac.setJaPaciente("Sim");
        } else {
            pac.setJaPaciente("Não");
        }
        
        pac.setConsultaRealizada("Não");
        pac.setReceitaObs("");
        
        ListaPacientes.Adicionar(pac);
        
        telaInicial.atualizarTabela();
        
        dispose();

    }

}
