/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import modelos.ListaPacientes;
import modelos.Pacientes;

/**
 *
 * @author thayn
 */
public class Consulta extends javax.swing.JFrame implements KeyListener, ActionListener {

    private TelaInicial telaInicial;
    private Pacientes paciente;
    private int PosPaciente;

    /**
     * Creates new form TelaDetalhesConsulta
     */
    public Consulta() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetalhesConsulta = new javax.swing.JPanel();
        lblDetalhesConsulta = new javax.swing.JLabel();
        jcbConsultaRealizada = new javax.swing.JCheckBox();
        lblReceitaObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceitaObs = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Detalhes da Consulta");

        lblDetalhesConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDetalhesConsulta.setText("Detalhes da consulta");

        jcbConsultaRealizada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbConsultaRealizada.setText("Consulta Realizada");

        lblReceitaObs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReceitaObs.setText("Receita e observações:");

        txtReceitaObs.setColumns(20);
        txtReceitaObs.setRows(5);
        jScrollPane1.setViewportView(txtReceitaObs);

        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetalhesConsultaLayout = new javax.swing.GroupLayout(pnlDetalhesConsulta);
        pnlDetalhesConsulta.setLayout(pnlDetalhesConsultaLayout);
        pnlDetalhesConsultaLayout.setHorizontalGroup(
            pnlDetalhesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalhesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(pnlDetalhesConsultaLayout.createSequentialGroup()
                        .addGroup(pnlDetalhesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetalhesConsulta)
                            .addComponent(jcbConsultaRealizada)
                            .addComponent(lblReceitaObs))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlDetalhesConsultaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnFinalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDetalhesConsultaLayout.setVerticalGroup(
            pnlDetalhesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetalhesConsulta)
                .addGap(18, 18, 18)
                .addComponent(jcbConsultaRealizada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReceitaObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDetalhesConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDetalhesConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        acaoBotao();

    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbConsultaRealizada;
    private javax.swing.JLabel lblDetalhesConsulta;
    private javax.swing.JLabel lblReceitaObs;
    private javax.swing.JPanel pnlDetalhesConsulta;
    private javax.swing.JTextArea txtReceitaObs;
    // End of variables declaration//GEN-END:variables

    public void MostrarTela(TelaInicial obj, int posPaciente) {
        this.telaInicial = obj;
        this.PosPaciente = posPaciente;
        this.paciente = ListaPacientes.getPaciente(posPaciente);
        setVisible(true);
        carregarFormulario();
        btnFinalizar.addActionListener(this);

    }

    private void carregarFormulario() {
        jcbConsultaRealizada.setSelected(false);
        btnFinalizar.setEnabled(false);

        txtReceitaObs.addKeyListener(this);

        if (this.paciente.getConsultaRealizada().equals("Sim")) {
            jcbConsultaRealizada.setSelected(true);
            jcbConsultaRealizada.setEnabled(false);
            btnFinalizar.setEnabled(false);
            txtReceitaObs.setEnabled(false);
        }

        txtReceitaObs.setText(this.paciente.getReceitaObs());
    }

    private void acaoBotao() {

        this.paciente.setReceitaObs(txtReceitaObs.getText());

        ListaPacientes.Atualizar(paciente, PosPaciente);

        telaInicial.atualizarTabela();

        dispose();
    }

    //KEYLISTENERS
    @Override
    public void keyTyped(KeyEvent e) {

    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getSource() == txtReceitaObs) {
            btnFinalizar.setEnabled(true);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnFinalizar) {
            jcbConsultaRealizada.setSelected(true);
            
            if (jcbConsultaRealizada.isSelected()) {
                this.paciente.setConsultaRealizada("Sim");
            }
        

        }
    }

}
