
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author thayn
 */
public class TelaGastoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form GastoCalorico
     */
    public TelaGastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Rb_Mulher = new javax.swing.JRadioButton();
        Rb_Homem = new javax.swing.JRadioButton();
        LbPeso = new javax.swing.JLabel();
        TxPeso = new javax.swing.JTextField();
        LbAltura = new javax.swing.JLabel();
        TxAltura = new javax.swing.JTextField();
        LbIdade = new javax.swing.JLabel();
        TxIdade = new javax.swing.JTextField();
        LbNivelAtividade = new javax.swing.JLabel();
        cb_NivelAtividade = new javax.swing.JComboBox<>();
        botaoCalcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLbGastoBasal = new javax.swing.JLabel();
        jLbGastoTotal = new javax.swing.JLabel();
        LbGastoBasal = new javax.swing.JLabel();
        LbGastoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cálculo de Gasto Calórico");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Rb_Mulher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rb_Mulher.setText("Mulher");
        Rb_Mulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_MulherActionPerformed(evt);
            }
        });

        Rb_Homem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rb_Homem.setText("Homem");
        Rb_Homem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_HomemActionPerformed(evt);
            }
        });

        LbPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbPeso.setText("Peso (Kg):");

        LbAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbAltura.setText("Altura (m):");

        LbIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbIdade.setText("Idade:");

        LbNivelAtividade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbNivelAtividade.setText("Nível de Atividade:");

        cb_NivelAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve (exercício leve 1 a 3 dias/semana)", "Moderado (exercício moderado 3 a 5 dias/semana)", "Ativo (exercício pesado 5 a 6 dias/semana)", "Extremamente ativo (exercício pesado diário)" }));
        cb_NivelAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_NivelAtividadeActionPerformed(evt);
            }
        });

        botaoCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoCalcular.setText("Calcular");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Rb_Mulher)
                        .addGap(88, 88, 88)
                        .addComponent(Rb_Homem))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LbNivelAtividade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_NivelAtividade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbAltura)
                            .addComponent(LbIdade)
                            .addComponent(LbPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxPeso)
                            .addComponent(TxAltura)
                            .addComponent(TxIdade))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rb_Homem)
                    .addComponent(Rb_Mulher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbPeso)
                    .addComponent(TxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbAltura)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TxAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbIdade)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbNivelAtividade)
                    .addComponent(cb_NivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(botaoCalcular)
                .addGap(38, 38, 38))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbGastoBasal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLbGastoBasal.setText("Gasto Basal:");

        jLbGastoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLbGastoTotal.setText("Gasto Total:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLbGastoBasal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbGastoBasal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLbGastoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbGastoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbGastoBasal)
                    .addComponent(LbGastoBasal, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbGastoTotal)
                    .addComponent(LbGastoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rb_HomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_HomemActionPerformed
        Rb_Mulher.setSelected(false);
    }//GEN-LAST:event_Rb_HomemActionPerformed

    private void cb_NivelAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_NivelAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_NivelAtividadeActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        calcBasal();
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void Rb_MulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_MulherActionPerformed
        Rb_Homem.setSelected(false);
    }//GEN-LAST:event_Rb_MulherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGastoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbAltura;
    private javax.swing.JLabel LbGastoBasal;
    private javax.swing.JLabel LbGastoTotal;
    private javax.swing.JLabel LbIdade;
    private javax.swing.JLabel LbNivelAtividade;
    private javax.swing.JLabel LbPeso;
    private javax.swing.JRadioButton Rb_Homem;
    private javax.swing.JRadioButton Rb_Mulher;
    private javax.swing.JTextField TxAltura;
    private javax.swing.JTextField TxIdade;
    private javax.swing.JTextField TxPeso;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JComboBox<String> cb_NivelAtividade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbGastoBasal;
    private javax.swing.JLabel jLbGastoTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public void calcBasal() {
        Double Peso;
        Double Altura;
        Double Idade;
        Double CalculoBasal;
        Double CalculoGastoTotal;
        String nvAtividade;

        if (TxPeso.getText().isEmpty() || TxAltura.getText().isEmpty() || TxIdade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
        } else if (Rb_Mulher.isSelected()) {
            String testePeso = TxPeso.getText();
            boolean palavraPeso = testePeso.matches("[0-9]{2,3}");
            String testeAltura = TxAltura.getText();
            boolean palavraAltura = testeAltura.matches("[0-9]{3}");
            String testeIdade = TxIdade.getText();
            boolean palavraIdade = testeIdade.matches("[0-9]{2}");

            if (palavraAltura == true && palavraPeso == true && palavraIdade == true) {
                Altura = Double.parseDouble(TxAltura.getText());
                Peso = Double.parseDouble(TxPeso.getText());
                Idade = Double.parseDouble(TxIdade.getText());

                //calculo
                CalculoBasal = 655 + (9.6 * Peso) + (1.9 * Altura) - (4.7 * Idade);
                LbGastoBasal.setText("é " + CalculoBasal);

                nvAtividade = cb_NivelAtividade.getSelectedItem().toString();
                if (nvAtividade == "Sedentário") {
                    CalculoGastoTotal = CalculoBasal * 1.2;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Leve (exercício leve 1 a 3 dias/semana)") {
                    CalculoGastoTotal = CalculoBasal * 1.375;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Moderado (exercício moderado 3 a 5 dias/semana)") {
                    CalculoGastoTotal = CalculoBasal * 1.55;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Ativo (exercício pesado 5 a 6 dias/semana)") {
                    CalculoGastoTotal = CalculoBasal * 1.725;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Extremamente ativo (exercício pesado diário)") {
                    CalculoGastoTotal = CalculoBasal * 1.9;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Peso deve ser no formato XX ou XXX, Altura no formato XXX e Idade no formato XX, sem pontos ou vígurlas ");
            }
        } else if (Rb_Homem.isSelected()) {
            String testePeso = TxPeso.getText();
            boolean palavraPeso = testePeso.matches("[0-9]{2,3}");
            String testeAltura = TxAltura.getText();
            boolean palavraAltura = testeAltura.matches("[0-9]{3}");
            String testeIdade = TxIdade.getText();
            boolean palavraIdade = testeIdade.matches("[0-9]{2}");

            if (palavraAltura == true && palavraPeso == true && palavraIdade == true) {
                Altura = Double.parseDouble(TxAltura.getText());
                Peso = Double.parseDouble(TxPeso.getText());
                Idade = Double.parseDouble(TxIdade.getText());

                //calculo
                CalculoBasal = 66 + (13.8 * Peso) + (5 * Altura) - (6.8 * Idade);
                LbGastoBasal.setText("é " + CalculoBasal);

                nvAtividade = cb_NivelAtividade.getSelectedItem().toString();
                if (nvAtividade == "Sedentário") {
                    CalculoGastoTotal = CalculoBasal * 1.2;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Leve (exercício leve 1 a 3 dias/semana)") {
                    CalculoGastoTotal = CalculoBasal * 1.375;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Moderado (exercício moderado 3 a 5 dias/semana)") {
                    CalculoGastoTotal = CalculoBasal * 1.55;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Ativo (exercício pesado 5 a 6 dias/semana)") {
                    CalculoGastoTotal = CalculoBasal * 1.725;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }
                if (nvAtividade == "Extremamente ativo (exercício pesado diário)") {
                    CalculoGastoTotal = CalculoBasal * 1.9;
                    LbGastoTotal.setText("é " + CalculoGastoTotal);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Peso deve ser no formato XX ou XXX, Altura no formato XXX e Idade no formato XX, sem pontos ou vígurlas ");
            }

        }

    }
}
